vladimir s.
git-courses/hillel-front-end-2017 pull request #11
Opened 2017-06-18 22:39 UTC by svladimir1010

something like this

2017-06-18 22:53 UTC, svladimir1010 commented
I think so everything

2017-06-19 15:10 UTC, vit-lebediev requested changes
This is not what was required in the task. Please review my comments and update PR accordingly.

2017-06-19 15:10 UTC, Malgin commented on students.txt
> + - spend time with my family or friends
You've added an item to someone else's description. This was NOT the task.

You need to add a list of your hobbies, plus extend your last name on line 13.

2017-06-19 23:10 UTC, closed without merging

2017-06-19 23:39 UTC, svladimir1010 commented
Здесь что то не так?