Some info about me
git-courses/hillel-front-end-2017 pull request #4
Opened 2017-06-14 13:49 UTC by MJ23M

2017-06-14 13:51 UTC, MJ23M commented
111

2017-06-15 11:11 UTC, vit-lebediev requested changes
In general, looks good. Just a few changes, and can be merged.

2017-06-15 11:11 UTC, Malgin commented on students.txt
> +Love videogames, especially Dota2. I like playing basketball and travelling to the mountains.
`to the mountains` -> `to mountains`
And please, start each sentence from a new line.

2017-06-19 06:36 UTC, vit-lebediev requested changes
Good, but still, I've asked to change the phrase from `to the mountains` to `to mountains`. You should use definite article 'the' when you speak about some specific mountains, not mountains in general.

2017-06-19 16:45 UTC, MJ23M commented
Add changes

2017-06-22 17:31 UTC, vit-lebediev approved these changes

2017-06-22 17:31 UTC, Malgin commented
Looks good. :shipit:

2017-06-22 17:31 UTC, merged